from . import OSCAddress, OSCFlavor


class SynesthesiaOSCFlavor(OSCFlavor):
    EVENTS = [
        OSCAddress('/audio/beat/beattime', (float,), description="Clock incrementing by 1 on each beat"),
        OSCAddress('/audio/beat/onbeat', (float,), description="1.0 if on a beat, falls back to 0.0"),
        # OSCAddress('/audio/beat/toggleonbeat?', (float,), description="1.0 if on a beat, falls back to 0.0"),
        OSCAddress('/audio/beat/randomonbeat', (float,), description="Random number between 0.0-1.0 on a beat"),
        OSCAddress('/audio/bpm/bpm', (float,), description="Estimated BPM, ~50-220"),
        OSCAddress('/audio/bpm/bpmconfidence', (float,), description="Confidence in estimated BPM, where 1.0 is high confidence of a steady BPM"),
        OSCAddress('/audio/bpm/bpmsin', (float,), description="Sine wave at BPM frequency"),
        OSCAddress('/audio/bpm/bpmsin2', (float,), description="Sine wave at half BPM frequency"),
        OSCAddress('/audio/bpm/bpmsin4', (float,), description="Sine wave at quarter BPM frequency"),
        OSCAddress('/audio/bpm/bpmtri', (float,), description="Triangle wave at BPM frequency"),
        OSCAddress('/audio/bpm/bpmtri2', (float,), description="Triangle wave at half BPM frequency"),
        OSCAddress('/audio/bpm/bpmtwitcher', (float,), description="Clock smoothly incrementing with each beat"),
        OSCAddress('/audio/energy/intensity', (float,), description="Overall intensity of audio"),
        # OSCAddress('/audio/energy/fadeinout?', (float,), description="Overall intensity of audio"),
        OSCAddress('/audio/hits/all', (float,), description="Audio hit across any band"),
        OSCAddress('/audio/hits/bass', (float,), description="Audio hit in the bass band"),
        OSCAddress('/audio/hits/high', (float,), description="Audio hit in the high band"),
        OSCAddress('/audio/hits/mid', (float,), description="Audio hit in the mid band"),
        OSCAddress('/audio/hits/midhigh', (float,), description="Audio hit in the mid-high band"),
        OSCAddress('/audio/level/all', (float,), description="Overall level of audio across all bands"),
        OSCAddress('/audio/level/bass', (float,), description="Overall level of audio in the bass band"),
        OSCAddress('/audio/level/high', (float,), description="Overall level of audio in the high band"),
        OSCAddress('/audio/level/mid', (float,), description="Overall level of audio in the mid band"),
        OSCAddress('/audio/level/midhigh', (float,), description="Overall level of audio in the mid-high band"),
        OSCAddress('/audio/level/raw', (float,), description="Raw audio level"),
        OSCAddress('/audio/presence/all', (float,), description="Presence of audio across all bands"),
        OSCAddress('/audio/presence/bass', (float,), description="Presence of audio in the bass band"),
        OSCAddress('/audio/presence/high', (float,), description="Presence of audio in the high band"),
        OSCAddress('/audio/presence/mid', (float,), description="Presence of audio in the mid band"),
        OSCAddress('/audio/presence/midhigh', (float,), description="Presence of audio in the mid-high band"),
        OSCAddress('/audio/time/all', (float,), description="Counter that increases with the presence of audio across all bands"),
        OSCAddress('/audio/time/bass', (float,), description="Counter that increases with the presence of audio in the bass band"),
        OSCAddress('/audio/time/curved', (float,), description="Similar to /audio/time/all but increases relative to the volume"),
        OSCAddress('/audio/time/high', (float,), description="Counter that increases with the presence of audio in the high band"),
        OSCAddress('/audio/time/mid', (float,), description="Counter that increases with the presence of audio in the mid band"),
        OSCAddress('/audio/time/midhigh', (float,), description="Counter that increases with the presence of audio in the mid-high band"),
    ]